---
pipeline:
  name: fcc-files-download
transform:
  image: publicintegrity/fcc-files-loader
  cmd:
  - bash
  stdin:
  - ./transforms/download.sh /pfs/files/ /pfs/out/
parallelism_spec:
  constant: 2
egress:
  URL: "s3://cpi-docs/fcc-files-loader"
input:
  pfs:
    name: files
    repo: fcc-files-list
    glob: /*
